name: Deploy VPS Interior Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Set variables
            CONTAINER_NAME="vps-backend"
            IMAGE_NAME="vps-backend"
            PORT="5000"
            PROJECT_DIR="VPS-Interior-BackEnd"
            REPO_URL="https://github.com/ghulammujtaba153/VPS-Interior-BackEnd.git"

            # Clone repo if not exists
            if [ ! -d "$PROJECT_DIR" ]; then
              git clone $REPO_URL
            fi

            cd $PROJECT_DIR

            # Pull latest code
            git fetch origin main
            git checkout main
            git pull origin main

            # Remove any container using the same port (safety)
            docker ps --filter "publish=$PORT" -q | xargs -r docker rm -f

            # Remove old container by name if still present (double safety)
            docker rm -f $CONTAINER_NAME || true

            # Build Docker image
            docker build -t $IMAGE_NAME .

            # Run Docker container
            docker run -d \
              --name $CONTAINER_NAME \
              --env-file .env \
              -p $PORT:$PORT \
              $IMAGE_NAME
          EOF
