name: Deploy VPS Interior Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Set variables
            CONTAINER_NAME="vsp-interior-backend"
            IMAGE_NAME="vsp-interior-app"
            PORT="5000"

            # Clone repo if not exists
            if [ ! -d "VPS-Interior-BackEnd" ]; then
              git clone https://github.com/ghulammujtaba153/VPS-Interior-BackEnd.git
            fi

            cd VPS-Interior-BackEnd

            # Pull latest code
            git fetch origin main
            git checkout main
            git pull origin main

            # Stop and remove existing container if running
            docker rm -f $CONTAINER_NAME || true

            # Build the image
            docker build -t $IMAGE_NAME .

            # Run the container
            docker run -d \
              --name $CONTAINER_NAME \
              --env-file .env \
              -p 5000:5000 \
              $IMAGE_NAME
          EOF
